name: DFeBrasil
on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'DFeBrasil.sln'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'DFeBrasil.sln'
  workflow_dispatch:

jobs:
  build:
    name: Compile and Unit Tests
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Restore NuGet packages
        working-directory: ./
        run: dotnet restore

      - name: Build
        working-directory: ./
        run: dotnet build -c Release --no-restore

      - name: UnitTests Nfce Danfe
        run: dotnet test -c Release --logger:"console;verbosity=normal" --no-build
        working-directory: ./tests/DFeBrasil.Nfce.Danfe.UnitTests